"""create memory_logs table

Revision ID: 1bf806c92718
Revises: fbf827869e55
Create Date: 2025-11-08 16:06:23.567721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bf806c92718'
down_revision: Union[str, None] = 'fbf827869e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task', sa.String(length=255), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_logs_agent'), 'memory_logs', ['agent'], unique=False)
    op.create_index(op.f('ix_memory_logs_date'), 'memory_logs', ['date'], unique=False)
    op.create_index(op.f('ix_memory_logs_task'), 'memory_logs', ['task'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_logs_task'), table_name='memory_logs')
    op.drop_index(op.f('ix_memory_logs_date'), table_name='memory_logs')
    op.drop_index(op.f('ix_memory_logs_agent'), table_name='memory_logs')
    op.drop_table('memory_logs')
    # ### end Alembic commands ###
