"""create mental_notes table

Revision ID: 25f1529917d6
Revises: 1bf806c92718
Create Date: 2025-11-08 17:49:40.067547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25f1529917d6'
down_revision: Union[str, None] = '1bf806c92718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mental_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mental_notes_session_id'), 'mental_notes', ['session_id'], unique=False)
    op.create_index(op.f('ix_mental_notes_start_time'), 'mental_notes', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mental_notes_start_time'), table_name='mental_notes')
    op.drop_index(op.f('ix_mental_notes_session_id'), table_name='mental_notes')
    op.drop_table('mental_notes')
    # ### end Alembic commands ###
