"""Add user_id, project_id, and embedding to mental_notes

Revision ID: 70bc4459ad00
Revises: fb1c8a41bc5d
Create Date: 2025-11-16 03:02:27.914230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70bc4459ad00'
down_revision: Union[str, None] = 'fb1c8a41bc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mental_notes', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('mental_notes', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.add_column('mental_notes', sa.Column('project_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_mental_notes_project_id'), 'mental_notes', ['project_id'], unique=False)
    op.create_index(op.f('ix_mental_notes_user_id'), 'mental_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill existing records with default values (using test UUID)
    op.execute("""
        UPDATE mental_notes
        SET user_id = '00000000-0000-0000-0000-000000000001', project_id = 'default'
        WHERE user_id IS NULL OR project_id IS NULL
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mental_notes_user_id'), table_name='mental_notes')
    op.drop_index(op.f('ix_mental_notes_project_id'), table_name='mental_notes')
    op.drop_column('mental_notes', 'project_id')
    op.drop_column('mental_notes', 'user_id')
    op.drop_column('mental_notes', 'embedding')
    # ### end Alembic commands ###
