"""add_log_date_and_content_to_mental_notes

Revision ID: 86e0c0f561a7
Revises: 1e3c984de032
Create Date: 2025-11-22 18:18:11.136717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '86e0c0f561a7'
down_revision: Union[str, None] = '1e3c984de032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory_logs', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.drop_index(op.f('ix_memory_logs_search_vector'), table_name='memory_logs', postgresql_using='gin')
    op.add_column('mental_notes', sa.Column('log_date', sa.DateTime(), nullable=False))
    op.add_column('mental_notes', sa.Column('content', sa.Text(), nullable=False))
    op.alter_column('mental_notes', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.create_index(op.f('ix_mental_notes_log_date'), 'mental_notes', ['log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mental_notes_log_date'), table_name='mental_notes')
    op.alter_column('mental_notes', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.drop_column('mental_notes', 'content')
    op.drop_column('mental_notes', 'log_date')
    op.create_index(op.f('ix_memory_logs_search_vector'), 'memory_logs', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('memory_logs', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    # ### end Alembic commands ###
