"""cleanup_mental_notes_schema

Revision ID: b94261ba8b2a
Revises: dfa7c227910d
Create Date: 2025-11-22 18:28:37.378216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b94261ba8b2a'
down_revision: Union[str, None] = 'dfa7c227910d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mental_notes', sa.Column('note_type', sa.String(length=50), nullable=False))
    op.add_column('mental_notes', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.alter_column('mental_notes', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_mental_notes_document_type'), table_name='mental_notes')
    op.drop_index(op.f('ix_mental_notes_log_date'), table_name='mental_notes')
    op.create_index(op.f('ix_mental_notes_note_type'), 'mental_notes', ['note_type'], unique=False)
    op.drop_column('mental_notes', 'document_type')
    op.drop_column('mental_notes', 'log_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mental_notes', sa.Column('log_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('mental_notes', sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_mental_notes_note_type'), table_name='mental_notes')
    op.create_index(op.f('ix_mental_notes_log_date'), 'mental_notes', ['log_date'], unique=False)
    op.create_index(op.f('ix_mental_notes_document_type'), 'mental_notes', ['document_type'], unique=False)
    op.alter_column('mental_notes', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('mental_notes', 'meta_data')
    op.drop_column('mental_notes', 'note_type')
    # ### end Alembic commands ###
