"""remove_start_time_from_mental_notes

Revision ID: dfa7c227910d
Revises: fe73cfbc638a
Create Date: 2025-11-22 18:20:44.370318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa7c227910d'
down_revision: Union[str, None] = 'fe73cfbc638a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mental_notes_start_time'), table_name='mental_notes')
    op.drop_column('mental_notes', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mental_notes', sa.Column('start_time', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_mental_notes_start_time'), 'mental_notes', ['start_time'], unique=False)
    # ### end Alembic commands ###
