"""add_document_type_to_mental_notes_and_memory_logs

Revision ID: f26216369632
Revises: 70bc4459ad00
Create Date: 2025-11-16 04:43:26.235719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26216369632'
down_revision: Union[str, None] = '70bc4459ad00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first to allow backfill
    op.add_column('memory_logs', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('mental_notes', sa.Column('document_type', sa.String(length=50), nullable=True))

    # Backfill existing records with their document types
    op.execute("""
        UPDATE memory_logs
        SET document_type = 'memory_log'
        WHERE document_type IS NULL
    """)

    op.execute("""
        UPDATE mental_notes
        SET document_type = 'mental_note'
        WHERE document_type IS NULL
    """)

    # Now make columns NOT NULL and create indexes
    op.alter_column('memory_logs', 'document_type', nullable=False)
    op.alter_column('mental_notes', 'document_type', nullable=False)

    op.create_index(op.f('ix_memory_logs_document_type'), 'memory_logs', ['document_type'], unique=False)
    op.create_index(op.f('ix_mental_notes_document_type'), 'mental_notes', ['document_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mental_notes_document_type'), table_name='mental_notes')
    op.drop_column('mental_notes', 'document_type')
    op.drop_index(op.f('ix_memory_logs_document_type'), table_name='memory_logs')
    op.drop_column('memory_logs', 'document_type')
    # ### end Alembic commands ###
